"""Generate thesis-ready assets from benchmark summary outputs."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def _latest_summary_dir(root: Path) -> Path:
    candidates = [p for p in root.iterdir() if p.is_dir()]
    if not candidates:
        raise FileNotFoundError(f"No benchmark summary directories found in {root}")
    return sorted(candidates, key=lambda p: p.name)[-1]


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _to_float(value: str) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _build_main_table(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    wanted_labels = {250, 1000, 4000}
    wanted_algorithms = {"supervised", "pseudolabel", "fixmatch", "mixmatch", "flexmatch"}

    table = []
    for row in rows:
        algorithm = row.get("algorithm", "")
        labels_total = row.get("labels_total", "")
        if algorithm not in wanted_algorithms:
            continue
        if labels_total == "":
            continue
        if int(labels_total) not in wanted_labels:
            continue
        table.append(
            {
                "run_name": row.get("run_name", ""),
                "config_path": row.get("config_path", ""),
                "algorithm": algorithm,
                "labels_total": labels_total,
                "best_test_acc": row.get("best_test_acc", ""),
                "epochs_completed": row.get("epochs_completed", ""),
                "expected_epochs": row.get("expected_epochs", ""),
                "status": row.get("status", ""),
                "notes": row.get("notes", ""),
                "log_path": row.get("log_path", ""),
            }
        )
    table.sort(key=lambda r: (int(r["labels_total"]), r["algorithm"]))
    return table


def _write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _write_latex_accuracy_table(path: Path, rows: list[dict[str, str]]) -> None:
    by_key: dict[tuple[str, int], list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        by_key[(r["algorithm"], int(r["labels_total"]))].append(r)

    def _status_score(status: str) -> int:
        if status == "complete":
            return 3
        if status == "partial":
            return 2
        if status == "missing":
            return 1
        return 0

    def _progress_ratio(r: dict[str, str]) -> float:
        completed = _to_float(r.get("epochs_completed", ""))
        expected = _to_float(r.get("expected_epochs", ""))
        if completed is None or expected is None or expected == 0:
            return 0.0
        return completed / expected

    def _pick_best(rows_for_key: list[dict[str, str]]) -> dict[str, str]:
        def _rank(r: dict[str, str]) -> tuple[int, float, float]:
            status = r.get("status", "")
            status_score = _status_score(status)
            acc = _to_float(r.get("best_test_acc", ""))
            acc_score = acc if acc is not None else float("-inf")
            progress = _progress_ratio(r)
            return (status_score, acc_score, progress)

        return max(rows_for_key, key=_rank)

    matrix: dict[tuple[str, int], str] = {}
    for key, candidates in by_key.items():
        r = _pick_best(candidates)
        status = r.get("status", "")
        acc = r.get("best_test_acc", "")

        if acc:
            cell = f"{acc}\\%"
        else:
            cell = "-"

        if status != "complete":
            cell = f"{cell} ({status})"

        matrix[key] = cell

    algorithms = ["supervised", "pseudolabel", "fixmatch", "mixmatch", "flexmatch"]
    labels = [250, 1000, 4000]

    lines = []
    lines.append("% Auto-generated by thesis_tools/generate_report_assets.py")
    lines.append("\\begin{tabular}{lccc}")
    lines.append("\\hline")
    lines.append("Method & 250 labels & 1000 labels & 4000 labels \\\\")
    lines.append("\\hline")
    for algo in algorithms:
        cells = [matrix.get((algo, l), "-") for l in labels]
        lines.append(f"{algo} & {cells[0]} & {cells[1]} & {cells[2]} \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_gap_report(path: Path, rows: list[dict[str, str]]) -> None:
    missing = [r for r in rows if r["status"] != "complete"]
    by_label: dict[str, list[dict[str, str]]] = defaultdict(list)
    for r in missing:
        by_label[r["labels_total"]].append(r)

    lines = []
    lines.append("# Remaining Experimental Gaps")
    lines.append("")
    lines.append(f"Generated at: {datetime.now().isoformat()}")
    lines.append("")
    if not missing:
        lines.append("All tracked benchmark slots are complete.")
    else:
        for label in sorted(by_label.keys(), key=int):
            lines.append(f"## Label Budget: {label}")
            lines.append("")
            for r in sorted(by_label[label], key=lambda x: x["algorithm"]):
                lines.append(
                    f"- {r['run_name'] or r['algorithm']}: status={r['status']}, best_acc={r['best_test_acc'] or '-'}, note={r['notes'] or '-'}"
                )
            lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate thesis report assets from benchmark summary")
    parser.add_argument("--summary-root", default="experiments/benchmark_summary", help="Root directory for benchmark summaries")
    parser.add_argument("--summary-dir", default=None, help="Specific summary directory name to use")
    parser.add_argument("--output-dir", default="experiments/final_report_assets", help="Directory to write thesis assets")
    args = parser.parse_args()

    summary_root = Path(args.summary_root)
    summary_dir = summary_root / args.summary_dir if args.summary_dir else _latest_summary_dir(summary_root)

    csv_path = summary_dir / "benchmark_summary.csv"
    json_path = summary_dir / "benchmark_summary.json"
    if not csv_path.exists() or not json_path.exists():
        raise FileNotFoundError(f"Missing benchmark_summary.csv/json in {summary_dir}")

    rows = _read_csv(csv_path)
    main_rows = _build_main_table(rows)

    out_root = Path(args.output_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    _write_csv(
        out_root / "accuracy_main_table.csv",
        main_rows,
        [
            "run_name",
            "config_path",
            "algorithm",
            "labels_total",
            "best_test_acc",
            "epochs_completed",
            "expected_epochs",
            "status",
            "notes",
            "log_path",
        ],
    )
    _write_latex_accuracy_table(out_root / "accuracy_main_table.tex", main_rows)
    _write_gap_report(out_root / "remaining_gaps.md", main_rows)

    with json_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    metadata = {
        "source_summary_dir": summary_dir.as_posix(),
        "generated_at": datetime.now().isoformat(),
        "record_count": len(payload.get("records", [])),
        "main_table_rows": len(main_rows),
    }
    (out_root / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"Using summary dir: {summary_dir.as_posix()}")
    print(f"Wrote: {(out_root / 'accuracy_main_table.csv').as_posix()}")
    print(f"Wrote: {(out_root / 'accuracy_main_table.tex').as_posix()}")
    print(f"Wrote: {(out_root / 'remaining_gaps.md').as_posix()}")
    print(f"Wrote: {(out_root / 'metadata.json').as_posix()}")


if __name__ == "__main__":
    main()
